# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_inv <- function(X) {
    .Call(`_IMeta_matrix_inv`, X)
}

lognormal_MLE <- function(Y) {
    .Call(`_IMeta_lognormal_MLE`, Y)
}

lognormal_FI <- function(Y, n, theta) {
    .Call(`_IMeta_lognormal_FI`, Y, n, theta)
}

pareto_QF <- function(u, theta) {
    .Call(`_IMeta_pareto_QF`, u, theta)
}

logdlnorm <- function(Y, n, theta) {
    .Call(`_IMeta_logdlnorm`, Y, n, theta)
}

logdbinom <- function(Y, mu) {
    .Call(`_IMeta_logdbinom`, Y, mu)
}

logdpois <- function(Y, mu) {
    .Call(`_IMeta_logdpois`, Y, mu)
}

lognormal_individual_IM <- function(Y, n, mu, gamma, theta_MLE) {
    .Call(`_IMeta_lognormal_individual_IM`, Y, n, mu, gamma, theta_MLE)
}

pareto_individual_IM <- function(Y, n, theta) {
    .Call(`_IMeta_pareto_individual_IM`, Y, n, theta)
}

logistic_individual_IM <- function(mu, mu_MLE, Y) {
    .Call(`_IMeta_logistic_individual_IM`, mu, mu_MLE, Y)
}

poisson_individual_IM <- function(mu, mu_MLE, Y) {
    .Call(`_IMeta_poisson_individual_IM`, mu, mu_MLE, Y)
}

valid_lognormal_individual_IM <- function(theta, Y, n, M) {
    .Call(`_IMeta_valid_lognormal_individual_IM`, theta, Y, n, M)
}

valid_pareto_individual_IM <- function(theta, Y, n, M) {
    .Call(`_IMeta_valid_pareto_individual_IM`, theta, Y, n, M)
}

valid_logistic_individual_IM <- function(theta, theta_MLE, Y, covariates, n, p, M) {
    .Call(`_IMeta_valid_logistic_individual_IM`, theta, theta_MLE, Y, covariates, n, p, M)
}

valid_poisson_individual_IM <- function(theta, theta_MLE, Y, covariates, n, p, M) {
    .Call(`_IMeta_valid_poisson_individual_IM`, theta, theta_MLE, Y, covariates, n, p, M)
}

lognormal_work_likeli <- function(theta, theta_MLE, J_ni, k) {
    .Call(`_IMeta_lognormal_work_likeli`, theta, theta_MLE, J_ni, k)
}

pareto_work_likeli <- function(theta, theta_MLE, J_ni, k) {
    .Call(`_IMeta_pareto_work_likeli`, theta, theta_MLE, J_ni, k)
}

logistic_work_likeli <- function(theta, theta_MLE, J_ni, p, k) {
    .Call(`_IMeta_logistic_work_likeli`, theta, theta_MLE, J_ni, p, k)
}

poisson_work_likeli <- function(theta, theta_MLE, J_ni, p, k) {
    .Call(`_IMeta_poisson_work_likeli`, theta, theta_MLE, J_ni, p, k)
}

lognormal_pl_mid_exact <- function(theta, theta_MLE, k, J_ni, n_i, M) {
    .Call(`_IMeta_lognormal_pl_mid_exact`, theta, theta_MLE, k, J_ni, n_i, M)
}

pareto_pl_mid_exact <- function(theta, theta_MLE, k, J_ni, n_i, M) {
    .Call(`_IMeta_pareto_pl_mid_exact`, theta, theta_MLE, k, J_ni, n_i, M)
}

logistic_pl_mid_exact <- function(theta, theta_MLE, k, J_ni, n_i, covariates, M) {
    .Call(`_IMeta_logistic_pl_mid_exact`, theta, theta_MLE, k, J_ni, n_i, covariates, M)
}

poisson_pl_mid_exact <- function(theta, theta_MLE, k, J_ni, n_i, covariates, M) {
    .Call(`_IMeta_poisson_pl_mid_exact`, theta, theta_MLE, k, J_ni, n_i, covariates, M)
}

lognormal_pl_mid_P <- function(theta, theta_dag, theta_MLE, k, J_ni, n_i, M) {
    .Call(`_IMeta_lognormal_pl_mid_P`, theta, theta_dag, theta_MLE, k, J_ni, n_i, M)
}

logistic_pl_mid_P <- function(theta, theta_dag, theta_MLE, k, J_ni, n_i, covariates, M) {
    .Call(`_IMeta_logistic_pl_mid_P`, theta, theta_dag, theta_MLE, k, J_ni, n_i, covariates, M)
}

poisson_pl_mid_P <- function(theta, theta_dag, theta_MLE, k, J_ni, n_i, covariates, M) {
    .Call(`_IMeta_poisson_pl_mid_P`, theta, theta_dag, theta_MLE, k, J_ni, n_i, covariates, M)
}

poisson_pl_mid_IS <- function(theta, theta_dag, theta_MLE, k, J_ni, n_i, covariates, M) {
    .Call(`_IMeta_poisson_pl_mid_IS`, theta, theta_dag, theta_MLE, k, J_ni, n_i, covariates, M)
}

