# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exponential_work_likeli <- function(theta, theta_MLE, J_ni, k) {
    .Call(`_IMdac_exponential_work_likeli`, theta, theta_MLE, J_ni, k)
}

exponential_pl_mid_P <- function(theta, theta_dag, theta_MLE, k, J_ni, n_i, M) {
    .Call(`_IMdac_exponential_pl_mid_P`, theta, theta_dag, theta_MLE, k, J_ni, n_i, M)
}

